---
# handlers file for ssh
- name: restart sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted

# handlers file for ufw
- name: reload ufw
  become: true
  community.general.ufw:
    state: reloaded

- name: Reload_zabbix
  become: true
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted

