---
# tasks file for wazuh

- name: Downaload Wazuh deb from curl
  ansible.builtin.get_url:
    url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.3-1_amd64.deb
    dest: /tmp/wazuh-agent.deb
    mode: '0440'
  when: ( ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' ) and ansible_architecture == "x86_64"
  register: Downaloaded
  
- name: Downaload Wazuh deb from curl
  ansible.builtin.get_url:
    url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.5.3-1_amd64.deb
    dest: /tmp/wazuh-agent.deb
    mode: '0440'
  when: ( ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' ) and ansible_architecture == "aarch64"
  register: Downaloaded
  
- name: Install the Wazuh.deb
  become: true
  ansible.builtin.shell:
    cmd: sudo WAZUH_MANAGER='dans-wazuh.lan' WAZUH_AGENT_GROUP='default' dpkg -i /tmp/wazuh-agent.deb
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' 
  ignore_errors: true

- name: Just force systemd to reread configs
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' 

- name: Enable and start wazuh-agent
  become: true
  ansible.builtin.service:
    name: wazuh-agent
    state: started
    enabled: yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' 
  ignore_errors: true

