
---

# wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb

- name: Download zabbix-release.deb
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
    dest: /tmp/zabbix-agent.deb
  when: ansible_architecture == "x86_64" and ansible_distribution == 'Ubuntu' 
  
- name: Download zabbix-release.deb
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-4+debian11_all.deb
    dest: /tmp/zabbix-agent.deb
  when: ansible_architecture == "x86_64" and ansible_distribution == 'Debian' 
  
- name: Download zabbix-release.deb
  ansible.builtin.get_url:
    url: wget https://repo.zabbix.com/zabbix/6.0/ubuntu-arm64/pool/main/z/zabbix-release/zabbix-release_6.0-5+ubuntu22.04_all.deb
    dest: /tmp/zabbix-agent.deb
  when: ansible_architecture == "arm64" and ansible_distribution == 'Ubuntu' 

# dpkg -i zabbix-release_6.0-4+ubuntu22.04_all.deb

- name: Install the zabbix .deb
  ansible.builtin.apt:
    deb: /tmp/zabbix-agent.deb
  when: ansible_distribution == 'Ubuntu' 

# apt update 

- name: Apt update
  ansible.builtin.apt:
    update_cache: true

# apt install zabbix-agent

- name: Install zabbix-agent
  ansible.builtin.apt:
    name: zabbix-agent
    state: present
  notify: Reload_zabbix
  when: ansible_distribution == 'Ubuntu' 

# systemctl enable zabbix-agent 

- name: daemon-reload 
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable zabbix-agent
  ansible.builtin.systemd:
    name: zabbix-agent
    enabled: true
  notify: Reload_zabbix

# systemctl restart zabbix-agent

- name: Allow 10050 UFW
  become: true
  community.general.ufw:
    rule: allow
    port: 10050
    src: '{{ item }}'
    proto: tcp
  loop: '{{ trusted_net }}'
  notify: reload ufw